services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: HeronDev
      POSTGRES_DB: heron
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - heron_default
  seq:
    image: datalust/seq:latest
    ports:
    - '5341:80'
    environment:
    - ACCEPT_EULA=Y
    networks:
    - heron_default
networks:
  heron_default:

volumes:
  dbdata: