// <auto-generated />
using System;
using HeronApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Data.Migrations
{
    [DbContext(typeof(HeronDBContext))]
    [Migration("20220210001041_SeedHeroDescriptionAndType")]
    partial class SeedHeroDescriptionAndType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeronApi.Data.Entities.HeroAbilityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUltimate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("HeroAblities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8f50d2c-513b-4b0d-923b-448233a54d61"),
                            Description = "Fires a dart that puts an enemy to sleep.",
                            HeroId = new Guid("13d7bac1-6962-46d8-b4e5-664d1ed7d0a1"),
                            IsUltimate = false,
                            Name = "Sleep Dart"
                        },
                        new
                        {
                            Id = new Guid("33977acb-67f7-47d2-967e-355a18195efc"),
                            Description = "Throws a grenade that heals and increses healing on allies, while damaging and preventing healing on enemies.",
                            HeroId = new Guid("13d7bac1-6962-46d8-b4e5-664d1ed7d0a1"),
                            IsUltimate = false,
                            Name = "Biotic Grenade"
                        },
                        new
                        {
                            Id = new Guid("e80bf53b-65a9-4189-9a21-393fcdacd494"),
                            Description = "Increases an ally's damge, while reducing damage taken.",
                            HeroId = new Guid("13d7bac1-6962-46d8-b4e5-664d1ed7d0a1"),
                            IsUltimate = true,
                            Name = "Nano Boost"
                        });
                });

            modelBuilder.Entity("HeronApi.Data.Entities.HeroEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13d7bac1-6962-46d8-b4e5-664d1ed7d0a1"),
                            Description = "Ana's versatile arsenal allows her to affect heroes all over the battlefield. Her Biotic Rifle rounds and Biotic Grenades heal allies and damage or impair enemies; her sidearm tranquilizes key targets, and Nano Boost gives one of her comrades a considerable increase in power.",
                            Name = "Ana",
                            Type = "Support"
                        },
                        new
                        {
                            Id = new Guid("cd77e568-d337-4d36-935f-7a5ed21ae705"),
                            Description = "Ashe quickly fires her rifle from the hip or uses her weapon's aim-down sights to line up a high damage shot. She blasts enemies by throwing dynamite, and her coach gun packs enough punch to put some distance between her and her foes. And Ashe is not alone, as she can call on her omnic ally Bob, to join the fray when the need arises.",
                            Name = "Ashe",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("14c6674f-103f-4692-9851-75d0a04a9714"),
                            Description = "Baptiste wields an assortment of experimental devices and weaponry to keep allies alive and eliminate threats under fierce conditions. A battle-hardened combat medic, he is just as capable of saving lives as he is taking out the enemy.",
                            Name = "Baptiste",
                            Type = "Support"
                        },
                        new
                        {
                            Id = new Guid("1e6fcfa4-8eeb-4044-86bb-ae7a605c5e52"),
                            Description = "Repair protocols and the ability to transform between stationary Assault, mobile Recon and devastating Tank configurations provide Bastion with a high probability of victory.",
                            Name = "Bastion",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("2c91c753-12fe-4856-a86a-5f7aa708fb00"),
                            Description = "Brigitte specializes in armor. She can throw Repair Packs to heal teammates, or automatically heal nearby allies when she damages foes with her Flail. Her Flail is capable of a wide swing to strike multiple targets, or a Whip Shot that stuns an enemy at range. When entering the fray, Barrier Shield provides personal defense while she attacks enemies with Shield Bash. Brigitte's ultimate ability, Rally, gives her a substantial short-term boost of speed and provides long-lasting armor to all her nearby allies.",
                            Name = "Brigitte",
                            Type = "Support"
                        },
                        new
                        {
                            Id = new Guid("312ba684-057b-4087-ac67-d087ee2d2d20"),
                            Description = "Armed with his Peacekeeper revolver, Cassidy takes out targets with deadeye precision and dives out of danger with eagle-like speed.",
                            Name = "Cassidy",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("31ae0ce9-4fd7-4f27-978e-7c0ac8eded83"),
                            Description = "D.Va's mech is nimble and powerful—its twin Fusion Cannons blast away with autofire at short range, and she can use its Boosters to barrel over enemies and obstacles, or deflect attacks with her projectile-dismantling Defense Matrix.",
                            Name = "D.Va",
                            Type = "Tank"
                        },
                        new
                        {
                            Id = new Guid("36c03343-024a-4140-bf33-d0081bd57159"),
                            Description = "Doomfist's cybernetics make him a highly-mobile, powerful frontline fighter. In addition to dealing ranged damage with his Hand Cannon, Doomfist can slam the ground, knock enemies into the air and off balance, or charge into the fray with his Rocket Punch. When facing a tightly packed group, Doomfist leaps out of view, then crashes down to earth with a spectacular Meteor Strike.",
                            Name = "Doomfist",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("39f4761b-02cc-4689-9993-6d096b7c49c9"),
                            Description = "Echo is an evolutionary robot programmed with a rapidly adapting artificial intelligence, versatile enough to fill multiple battlefield combat roles.",
                            Name = "Echo",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("4828b36a-7d8a-418f-96a0-038c881cbc1c"),
                            Description = "Genji flings precise and deadly Shuriken at his targets, and uses his technologically-advanced katana to deflect projectiles or deliver a Swift Strike that cuts down",
                            Name = "Genji",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("4bca8882-a741-447c-b8bf-80a2f75f34ca"),
                            Description = "Hanzo's versatile arrows can reveal his enemies or fragment to strike multiple targets. He can scale walls to fire his bow from on high, or summon a titanic spirit dragon.",
                            Name = "Hanzo",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("5572ee56-0f5a-466b-bdb7-d72032b8f25c"),
                            Description = "Junkrat's area-denying armaments include a Frag Launcher that lobs bouncing grenades, Concussion Mines that send enemies flying, and Steel Traps that stop foes dead in their tracks.",
                            Name = "Junkrat",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("5f94bf75-2400-4145-ab6a-475728f6f559"),
                            Description = "On the battlefield, Lúcio's cutting-edge Sonic Amplifier buffets enemies with projectiles and knocks foes back with blasts of sound. His songs can both heal his team or boost their movement speed, and he can switch between tracks on the fly.",
                            Name = "Lucio",
                            Type = "Support"
                        },
                        new
                        {
                            Id = new Guid("69346bd9-da97-4e0b-a88f-0221e41cc0b3"),
                            Description = "Mei's weather-altering devices slow opponents and protect locations. Her Endothermic Blaster unleashes damaging icicles and frost streams, and she can Cryo-Freeze herself to guard against counterattacks, or obstruct the opposing team's movements with an Ice Wall.",
                            Name = "Mei",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("6dcddb81-22e3-4b1b-835c-01cb1328ce50"),
                            Description = "Mercy's Valkyrie Suit helps keep her close to teammates like a guardian angel; healing, resurrecting or strengthening them with the beams emanating from her Caduceus Staff.",
                            Name = "Mercy",
                            Type = "Support"
                        },
                        new
                        {
                            Id = new Guid("721ba171-0e14-4bc0-bb7d-5b7ce24429a2"),
                            Description = "Moira's biotic abilities enable her to contribute healing or damage in any crisis. While Biotic Grasp gives Moira short-range options, her Biotic Orbs contribute longer-range, hands-off damage and healing; she can also Fade to escape groups or remain close to allies in need of support. Once she's charged Coalescence, Moira can save multiple allies from elimination at once or finish off weakened enemies.",
                            Name = "Moira",
                            Type = "Support"
                        },
                        new
                        {
                            Id = new Guid("73b2abd0-73c9-4d20-a42d-9ffec155ccfe"),
                            Description = "Orisa serves as the central anchor of her team, and defends her teammates from the frontline with a protective barrier. She can attack from long range, fortify her own defenses, launch graviton charges to slow and move enemies, and deploy a Supercharger to boost the damage output of multiple allies at once.",
                            Name = "Orisa",
                            Type = "Tank"
                        },
                        new
                        {
                            Id = new Guid("81828968-6173-4c2e-87a5-e13eae5598ad"),
                            Description = "Soaring through the air in her combat armor, and armed with a launcher that lays down high-explosive rockets, Pharah is a force to be reckoned with.",
                            Name = "Pharah",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("9473a0a1-b9ea-470f-bc22-a8f6e3d3f1e7"),
                            Description = "Hellfire Shotguns, the ghostly ability to become immune to damage, and the power to step between shadows make Reaper one of the deadliest beings on Earth.",
                            Name = "Reaper",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("a0b92948-70c1-4627-8f7a-ed7e1d40c28f"),
                            Description = "Clad in powered armor and swinging his hammer, Reinhardt leads a rocket-propelled charge across the battleground and defends his squadmates with a massive energy barrier.",
                            Name = "Reinhardt",
                            Type = "Tank"
                        },
                        new
                        {
                            Id = new Guid("a6a86d93-69c6-476e-8f3e-3b7782179f0b"),
                            Description = "Roadhog uses his signature Chain Hook to pull his enemies close before shredding them with blasts from his Scrap Gun. He's hardy enough to withstand tremendous damage, and can recover his health with a short breather.",
                            Name = "Roadhog",
                            Type = "Tank"
                        },
                        new
                        {
                            Id = new Guid("c0e9f882-bb15-43c4-b052-fd8126609ebb"),
                            Description = "Sigma is an eccentric astrophysicist and volatile tank who gained the power to control gravity in an orbital experiment gone wrong. Manipulated by Talon and deployed as a living weapon, Sigma's presence on the battlefield cannot be ignored.",
                            Name = "Sigma",
                            Type = "Tank"
                        },
                        new
                        {
                            Id = new Guid("c524d03c-f4a9-4b5c-afa2-cc1cb2d6f640"),
                            Description = "Armed with cutting-edge weaponry, including an experimental pulse rifle that's capable of firing spirals of high-powered Helix Rockets, Soldier: 76 has the speed and support know-how of a highly trained warrior.",
                            Name = "Soldier: 76",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("c53bebcf-7503-44aa-b84d-e9068fcf847b"),
                            Description = "Stealth and debilitating attacks make Sombra a powerful infiltrator. Her hacking can disrupt her enemies, ensuring they're easier to take out, while her EMP provides the upper hand against multiple foes at once. Sombra's ability to Translocate and camouflage herself makes her a hard target to pin down.",
                            Name = "Sombra",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("d13bd682-16ad-45dd-9694-5009fc2e15d4"),
                            Description = "Symmetra utilizes her Photon Projector to dispatch adversaries, shield her associates, construct teleportation pads and deploy particle-blasting Sentry Turrets.",
                            Name = "Symmetra",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("da360eea-e946-4056-a9dd-3d5bc6cd3fd5"),
                            Description = "Torbjörn's extensive arsenal includes a rivet gun, hammer, and a personal forge that he can use to build turrets.",
                            Name = "Torbjörn",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("db92993e-f997-4b99-9708-5f04bb4b24cb"),
                            Description = "Toting twin pulse pistols, energy-based time bombs, and rapid-fire banter, Tracer is able to \"blink\" through space and rewind her personal timeline as she battles to right wrongs the world over.",
                            Name = "Tracer",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("f11983cd-457f-47d1-8170-82be0113e033"),
                            Description = "Widowmaker equips herself with whatever it takes to eliminate her targets, including mines that dispense poisonous gas, a visor that grants her squad infra-sight, and a powerful sniper rifle that can fire in fully-automatic mode.",
                            Name = "Widowmaker",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("f25dd3c1-3d5a-47dc-ae53-ea0137654d35"),
                            Description = "Winston wields impressive inventions—a jump pack, electricity-blasting Tesla Cannon, portable shield projector and more—with literal gorilla strength.",
                            Name = "Winston",
                            Type = "Tank"
                        },
                        new
                        {
                            Id = new Guid("f8a29d50-838a-42f8-ae9d-0e907e283d48"),
                            Description = "Wrecking Ball rolls across the battlefield, using his arsenal of weapons and his mech's powerful body to crush his enemies.",
                            Name = "Wrecking Ball",
                            Type = "Tank"
                        },
                        new
                        {
                            Id = new Guid("fc3d9b4b-c95b-4b5b-abd9-7ca6adc1d964"),
                            Description = "Deploying powerful personal barriers that convert incoming damage into energy for her massive Particle Cannon, Zarya is an invaluable asset on the front lines of any battle.",
                            Name = "Zarya",
                            Type = "Damage"
                        },
                        new
                        {
                            Id = new Guid("fe52b22a-90c3-4e15-900a-b97d9caabab1"),
                            Description = "Zenyatta calls upon orbs of harmony and discord to heal his teammates and weaken his opponents, all while pursuing a transcendent state of immunity to damage.",
                            Name = "Zenyatta",
                            Type = "Support"
                        });
                });

            modelBuilder.Entity("HeroUpdateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeveloperComments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("HeroAbilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HeroAbilityId");

                    b.HasIndex("ReleaseId");

                    b.ToTable("HeroUpdates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c4fe85c7-d7ea-4c4e-b25b-182504a96b0f"),
                            ChangeNotes = "Change from 45 to 50 healing",
                            DeveloperComments = "A generic developer comment 1",
                            HeroAbilityId = new Guid("33977acb-67f7-47d2-967e-355a18195efc"),
                            ReleaseId = new Guid("2261cae5-98f8-48d9-bcc8-b798b2e269c2")
                        },
                        new
                        {
                            Id = new Guid("4cd59c55-4d11-44fa-9108-6a63564baaee"),
                            ChangeNotes = "Change from 40 to 45 healing",
                            DeveloperComments = "A generic developer comment 2",
                            HeroAbilityId = new Guid("33977acb-67f7-47d2-967e-355a18195efc"),
                            ReleaseId = new Guid("2261cae5-98f8-48d9-bcc8-b798b2e269c2")
                        },
                        new
                        {
                            Id = new Guid("7d473fdd-3b07-4f4a-997d-5963f91e1ced"),
                            ChangeNotes = "Increase charge time from 4s to 5s",
                            DeveloperComments = "A generic developer comment 3",
                            HeroAbilityId = new Guid("e80bf53b-65a9-4189-9a21-393fcdacd494"),
                            ReleaseId = new Guid("2261cae5-98f8-48d9-bcc8-b798b2e269c2")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReleaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Releases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2261cae5-98f8-48d9-bcc8-b798b2e269c2"),
                            ReleaseDate = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "OVERWATCH RETAIL PATCH NOTES - JANUARY 25, 2022"
                        },
                        new
                        {
                            Id = new Guid("0577db42-37f3-4445-bf6d-e0e3ab24fea9"),
                            ReleaseDate = new DateTime(2021, 12, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "OVERWATCH RETAIL PATCH NOTES - JANUARY 25, 2022"
                        },
                        new
                        {
                            Id = new Guid("70127cd1-c31f-49ec-a450-5ccde6dedcb7"),
                            ReleaseDate = new DateTime(2021, 12, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "OVERWATCH RETAIL PATCH NOTES - JANUARY 25, 2022"
                        },
                        new
                        {
                            Id = new Guid("2ea849bb-335c-4d50-bf23-52fd52acd457"),
                            ReleaseDate = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "OVERWATCH RETAIL PATCH NOTES - JANUARY 25, 2022"
                        },
                        new
                        {
                            Id = new Guid("403e0c1b-f8a1-4180-84dc-f55b48e89f62"),
                            ReleaseDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "OVERWATCH RETAIL PATCH NOTES - JANUARY 25, 2022"
                        });
                });

            modelBuilder.Entity("HeronApi.Data.Entities.HeroAbilityEntity", b =>
                {
                    b.HasOne("HeronApi.Data.Entities.HeroEntity", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("HeroUpdateEntity", b =>
                {
                    b.HasOne("HeronApi.Data.Entities.HeroAbilityEntity", "HeroAbility")
                        .WithMany()
                        .HasForeignKey("HeroAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReleaseEntity", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeroAbility");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
