apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: herostats-dev-cert
spec:
  dnsNames:
    - herostats.dev
  secretName: herostats-dev-cert
  issuerRef:
    name: digitalocean-issuer
    kind: ClusterIssuer
