FROM node:16-alpine as build

# Context will be root dir not /app because of github action weirdness
# https://github.com/moby/buildkit/issues/1684

COPY ./app/package.json /app/package.json
COPY ./app/package-lock.json /app/package-lock.json

RUN cd /app; npm ci

COPY ./app /app

RUN cd /app; npm run build

FROM nginx:alpine as runtime

COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

# TODO: use non-root user
EXPOSE 80
