version: "3.7"

services: 
  # api:
  #   image: webpack
  #   build :
  #     context: ../../
  #     dockerfile: ./docker/build/dockerfile
  #   ports: 
  #     - 4204:4204
  #   volumes:
  #     - ../../:/bindmount:rw
  #     - node_modules:/src/node_modules

  api:
    image: serve
    build:
      context: ../../
      dockerfile: ./docker/serve/dockerfile
    ports:
      - 4204:4204
    volumes: 
      - ../../:/bindmount:rw
      - node_modules:/src/node_modules
    networks:
      - dev_default

volumes:
  node_modules:

networks:
  dev_default: