FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /api

COPY ./api/api.csproj api.csproj
RUN dotnet restore

COPY ./api .
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV ASPNETCORE_URLS="http://*:8080,https://*:4443"
COPY --from=build /api/out .

EXPOSE 8080
EXPOSE 4443

ENTRYPOINT [ "dotnet", "aspnetapp.dll" ]